services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'bmanduca'
      MYSQL_PASSWORD: 'mand@42#'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'mand@42#'
      MYSQL_TCP_PORT: '3307'
    ports:
      - "3307:3307"
    expose:
      # Opens port 3307 on the container
      - '3307'
    volumes:
      - /Users/brunnomanduca/dev/mysql:/var/lib/mysql