'''
    PRIMEIRA CALCULADORA

    - UM NÚMERO É DIVIDO EM 3 PARTES IGUAIS

    - A PRIMEIRA PARTE É DIVIDA EM 4 E SEU RESULTADO SOMADO A 7. APÓS ISSO, 
    O RESULTADO É ELEVADO AO QUADRADO E MULTIPLICADO POR UM VALOR DE 0.257

    - A SEGUNDA PARTE É ELEVADA A POTÊNCIA DE 2.121, DIVIDA POR 5 E SOMADO 1.

    - A TERCEIRA PARTE SE MANTEM NO MESMO VALOR.

    -> POR FIM, É SOMADO ESSES 3 VALORES E ENTREGUE O RESULTADO.

'''